### ISSUE TITLE
Update the README with instructions how to run the app

### ISSUE THREAD

**Issue by Connor-Quinny** [The-Nobodies-SDD/plateable#50]
I've done npm install and npm start but I'm only seeing a white screen

**Comment by martin-stefan** [comment]
Currently the application is in development for a school project. If you wish to run the application, ensure that you are on the dev branch.

**Comment by Connor-Quinny** [comment]
I'm on the dev branch but not sure how to run the app. I've tried npm start but it's just a white screen.

**Comment by martin-stefan** [comment]
That is most likely the result of a missing firebase key which is private to all but the development team for the school project.
